import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import { setCanonical, resetCanonical, setSocialMeta, resetSocialMeta } from "@/lib/canonical";
import { blogPosts } from "@/data/blogPosts";
import { fetchCmsBlogPosts, formatCmsDate, type CmsBlogPost } from "@/lib/cmsBlog";

interface UnifiedPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  displayDate: string;
  sortKey: number;
}

const Blog = () => {
  const [cmsPosts, setCmsPosts] = useState<CmsBlogPost[]>([]);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setCanonical("/blog");
    setSocialMeta({
      title: "Detach Blog – App Blocker Tips & Screen Time Advice",
      description:
        "Read the Detach blog for tips on blocking social media, reducing screen time, and staying focused with the Detach app blocker.",
      path: "/blog",
      type: "website",
    });
    fetchCmsBlogPosts().then((posts) => {
      setCmsPosts(posts);
      setLoaded(true);
    });
    return () => {
      resetCanonical();
      resetSocialMeta();
    };
  }, []);

  const staticSlugs = new Set(blogPosts.map((p) => p.slug));
  const merged: UnifiedPost[] = [
    ...blogPosts.map((p) => ({
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt,
      date: p.date,
      displayDate: formatCmsDate(p.date),
      sortKey: new Date(p.date).getTime() || 0,
    })),
    ...cmsPosts
      .filter((p) => !staticSlugs.has(p.slug))
      .map((p) => {
        const raw = p.meta_description ?? p.excerpt ?? "";
        const cleaned = raw
          .replace(new RegExp(`^\\s*${p.title.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}\\s*!?\\s*`, "i"), "")
          .replace(/\s*!\s+/g, " ")
          .replace(/Article generated by BabyLoveGrowth\.?/gi, "")
          .trim();
        return {
          slug: p.slug,
          title: p.title,
          excerpt: cleaned || raw,
          date: p.published_at,
          displayDate: formatCmsDate(p.published_at),
          sortKey: new Date(p.published_at).getTime() || 0,
        };
      }),

  ].sort((a, b) => b.sortKey - a.sortKey);

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <main className="pt-24 pb-16 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4 text-center">
            Detach <span className="text-gradient">Blog</span>
          </h1>
          <p className="text-center text-muted-foreground text-lg mb-12 max-w-xl mx-auto">
            Tips and insights on reducing screen time, blocking social media, and staying focused with the Detach app
            blocker.
          </p>

          <div className="space-y-6">
            {merged.map((post) => (
              <Link
                key={post.slug}
                to={`/blog/${post.slug}`}
                className="glass-card p-6 block hover:border-primary/30 transition-colors group"
              >
                <p className="text-xs text-muted-foreground mb-2">{post.displayDate}</p>
                <h2 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors">{post.title}</h2>
                <p className="text-muted-foreground mb-4">{post.excerpt}</p>
                <span className="inline-flex items-center gap-1 text-primary font-semibold text-sm">
                  Read more <ArrowRight className="w-3 h-3" />
                </span>
              </Link>
            ))}
            {!loaded && cmsPosts.length === 0 && (
              <p className="text-center text-muted-foreground text-sm">Loading latest posts…</p>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Blog;
