// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-product-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_product_info_default = defineTool({
  name: "get_product_info",
  title: "Get product info",
  description: "Return current details about Pause, the free iPhone app and website blocker.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Pause",
      tagline: "A strict app and website blocker built to make your limits harder to undo impulsively.",
      price: "Free right now",
      platform: "iPhone only",
      account_required: false,
      ads: false,
      blocking_methods: ["Pause", "Schedule", "Time Limit", "Open Limit", "Friction Lock"],
      app_store_url: null,
      website: "https://pauseappblocker.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-site-links.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_site_links_default = defineTool2({
  name: "get_site_links",
  title: "Get site links",
  description: "Return the key public URLs on pauseappblocker.com so assistants can link users to the right page.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const links = {
      home: "https://pauseappblocker.com/",
      blog: "https://pauseappblocker.com/blog",
      remove_ignore_limit_guide: "https://pauseappblocker.com/blog/remove-ignore-limit-screen-time",
      contact: "https://pauseappblocker.com/contact",
      privacy_policy: "https://pauseappblocker.com/privacy-policy",
      terms: "https://pauseappblocker.com/terms",
      app_store: null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(links, null, 2) }],
      structuredContent: links
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pause-mcp",
  title: "Pause",
  version: "0.1.0",
  instructions: "Public tools for pauseappblocker.com. Use `get_product_info` for current Pause features and availability; use `get_site_links` for canonical page URLs.",
  tools: [get_product_info_default, get_site_links_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
